#! /bin/bash

code --install-extension adpyke.vscode-sql-formatter
code --install-extension akamud.vscode-theme-onedark
code --install-extension amazonwebservices.aws-toolkit-vscode
code --install-extension bierner.color-info
code --install-extension cschlosser.doxdocgen
code --install-extension DaltonMenezes.aura-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension fabiospampinato.vscode-todo-plus
code --install-extension foxundermoon.shell-format
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ms-vscode-remote.remote-ssh
code --install-extension ms-vscode-remote.remote-ssh-edit
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.cpptools-themes
code --install-extension ms-vscode.hexeditor
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.remote-explorer
code --install-extension pflannery.vscode-versionlens
code --install-extension PKief.material-icon-theme
code --install-extension pranaygp.vscode-css-peek
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension ritwickdey.LiveServer
code --install-extension roblourens.vscode-nand2tetris-hdl
code --install-extension rust-lang.rust-analyzer
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension tauri-apps.tauri-vscode
code --install-extension tldraw-org.tldraw-vscode
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-gradle
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension yzhang.markdown-all-in-one
